In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
x = np.array(range(10))

In [9]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
y = x * 2 - 3
print(y)

[-3 -1  1  3  5  7  9 11 13 15]


In [13]:
y = np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
id = np.identity(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
forty = np.zeros((1, 40))
print(forty)
forty = forty.reshape((8, 5))
print(forty)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
